### ISSUE TITLE
Error in Jupyter Notebook & which checkpoint to load?

### ISSUE THREAD

**Issue by YianZhang** [lena-voita/description-length-probing#2]
Hi Lena,

I am trying to reproduce your edge probing experiments (Description Length and Random Models). It seems some cells are deleted in this [notebook](https://github.com/lena-voita/description-length-probing/blob/master/jiant/mdl_eval_notebooks/Eval_MDL_variational_code.ipynb). For example, if I run the notebook sequentially, Cell 24 will report a key error. Would you please make sure the same experiment can be reproduced by running the cells sequentially from top to the bottom? Thanks a lot!

Also, the SRL result generated by the notebook matches that reported in the paper, but why do you load checkpoint 400? 400 validations seem to be much less than 200 epochs, which is claimed in the paper.

Thank you for your help in advance!

**Comment by lena-voita** [comment]
(discussed over email, updated the notebook)
